notifications:
  slack: uw-cse:O3kA2v8PDrUzH6YTuMfVUy8z
language: node_js
node_js:
  - "10.15.1"
env:
  global:
    - RACKET_DIR=~/racket
    - RACKET_VERSION="7.0"
    - Z3_VERSION="4.7.1"
    - Z3_DISTRIB="z3-4.7.1-x64-ubuntu-14.04"
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - curl -L -O https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/${Z3_DISTRIB}.zip
  - unzip ${Z3_DISTRIB}.zip
  - export PATH="${RACKET_DIR}/bin:${PWD}/${Z3_DISTRIB}/bin:${PATH}"
script:
  - make sanity test
