language: c
env:
  global:
    - RACKET_DIR=~/racket
    - RACKET_VERSION="6.9"
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
script:
  - make test
