#lang racket
(define (pid m)
  (let* ((t 0.0)
        (kp 9.4514)
        (ki 0.69006)
        (kd 2.8454)
        (invdt 5.0)
        (dt 0.2)
        (c 0.0)
        (eold 0.0)
        (i0 0.0)
        (e (- c m))
        (p (* kp e))
        (i (+ i0 (* (* ki dt) e)))
        (d (* (* kd invdt) (- e eold)))
        (r (+ (+ p i) d))
        (eold e)
        (t (+ t dt))
        )
        (* (+ m 0.01) r)
   )    
)